package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "title": "Expense Tracker API",
    "version": "1.0",
    "description": "Backend API for offline-first shared expense tracking."
  },
  "basePath": "/",
  "schemes": [
    "http",
    "https"
  ],
  "securityDefinitions": {
    "BearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header",
      "description": "JWT bearer token. Format: Bearer <token>"
    },
    "ApiKeyAuth": {
      "type": "apiKey",
      "name": "X-API-Key",
      "in": "header",
      "description": "Server API key generated by /api/v1/auth/api-keys"
    }
  },
  "paths": {
    "/": {
      "get": {
        "summary": "Service info",
        "responses": {
          "200": { "description": "Service metadata and links" }
        }
      }
    },
    "/healthz": {
      "get": {
        "summary": "Health check",
        "responses": {
          "200": { "description": "OK" }
        }
      }
    },
    "/signup": {
      "get": {
        "summary": "Signup page",
        "responses": {
          "200": { "description": "Static signup HTML" }
        }
      }
    },
    "/api/v1/auth/register": {
      "post": {
        "summary": "Register a user account",
        "responses": {
          "200": { "description": "Registered successfully" },
          "400": { "description": "Invalid request" }
        }
      }
    },
    "/api/v1/auth/login": {
      "post": {
        "summary": "Login with email and password",
        "responses": {
          "200": { "description": "Login success (JWT returned)" },
          "401": { "description": "Unauthorized" }
        }
      }
    },
    "/api/v1/auth/api-keys/authenticate": {
      "post": {
        "summary": "Authenticate using API key",
        "responses": {
          "200": { "description": "API key accepted" },
          "401": { "description": "Unauthorized" }
        }
      }
    },
    "/api/v1/auth/api-keys": {
      "post": {
        "summary": "Create API key",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "responses": {
          "200": { "description": "API key created" },
          "401": { "description": "Unauthorized" }
        }
      }
    },
    "/api/v1/sync": {
      "post": {
        "summary": "Sync local state to server",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "responses": {
          "200": { "description": "Sync success" },
          "401": { "description": "Unauthorized" }
        }
      }
    },
    "/api/v1/groups": {
      "post": {
        "summary": "Create group/household",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "responses": {
          "200": { "description": "Group created" },
          "401": { "description": "Unauthorized" }
        }
      }
    },
    "/api/v1/entries": {
      "post": {
        "summary": "Create transaction entry (group inferred from auth context)",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "responses": {
          "200": { "description": "Entry created" },
          "400": { "description": "Invalid request" },
          "401": { "description": "Unauthorized" }
        }
      }
    },
    "/api/v1/groups/{groupId}/accounts": {
      "get": {
        "summary": "List accounts",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "parameters": [
          { "name": "groupId", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Accounts list" },
          "401": { "description": "Unauthorized" }
        }
      },
      "post": {
        "summary": "Create account",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "parameters": [
          { "name": "groupId", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Account created" },
          "400": { "description": "Invalid request" },
          "401": { "description": "Unauthorized" }
        }
      }
    },
    "/api/v1/groups/{groupId}/categories": {
      "get": {
        "summary": "List categories",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "parameters": [
          { "name": "groupId", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Categories list" },
          "401": { "description": "Unauthorized" }
        }
      },
      "post": {
        "summary": "Create category",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "parameters": [
          { "name": "groupId", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Category created" },
          "400": { "description": "Invalid request" },
          "401": { "description": "Unauthorized" }
        }
      }
    },
    "/api/v1/groups/{groupId}/expenses": {
      "get": {
        "summary": "List transactions/expenses",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "parameters": [
          { "name": "groupId", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Expenses list" },
          "401": { "description": "Unauthorized" }
        }
      },
      "post": {
        "summary": "Create transaction/expense",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "parameters": [
          { "name": "groupId", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Expense created" },
          "400": { "description": "Invalid request" },
          "401": { "description": "Unauthorized" }
        }
      }
    },
    "/api/v1/groups/{groupId}/transactions": {
      "get": {
        "summary": "List transactions alias",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "parameters": [
          { "name": "groupId", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Transactions list" },
          "401": { "description": "Unauthorized" }
        }
      },
      "post": {
        "summary": "Create transaction alias",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "parameters": [
          { "name": "groupId", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Transaction created" },
          "400": { "description": "Invalid request" },
          "401": { "description": "Unauthorized" }
        }
      }
    },
    "/api/v1/groups/{groupId}/adjustments": {
      "get": {
        "summary": "List manual category adjustments",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "parameters": [
          { "name": "groupId", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Adjustments list" },
          "401": { "description": "Unauthorized" }
        }
      },
      "post": {
        "summary": "Create manual category adjustment",
        "security": [{ "BearerAuth": [] }, { "ApiKeyAuth": [] }],
        "parameters": [
          { "name": "groupId", "in": "path", "required": true, "type": "string" }
        ],
        "responses": {
          "200": { "description": "Adjustment created" },
          "400": { "description": "Invalid request" },
          "401": { "description": "Unauthorized" }
        }
      }
    }
  }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Expense Tracker API",
	Description:      "Backend API for offline-first shared expense tracking.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
